"""ChroniQ Seed Data Mirroring Frontend Mock Seeds."""

SEED_HOSPITAL = {
    "custom_id": "hosp_city_01",
    "name": "City Hospital",
    "code": "CITY",
    "city": "Chennai",
    "address": "42 Anna Salai, Thousand Lights, Chennai 600006",
    "phone": "+91 44 2829 0000",
    "email": "admin@cityhospital.example.com",
    "location": {
        "type": "Point",
        "coordinates": [80.2508, 13.0604],
    },
    "timings": "24x7",
    "facilities": [
        "Emergency & Trauma",
        "ICU",
        "Diagnostic Imaging",
        "In-House Pharmacy",
        "Ambulance 24x7",
        "Blood Bank",
    ],
    "rating_avg": 4.6,
    "rating_count": 1420,
    "status": "active",
    "settings": {
        "grace_period_minutes": 10,
        "cancel_window_hours": 2,
        "slot_hold_minutes": 5,
        "walk_ins_enabled": True,
    },
}

SEED_DEPARTMENTS = [
    {
        "custom_id": "dept_card",
        "hospital_id": "hosp_city_01",
        "name": "Cardiology",
        "code": "CARD",
        "room": "Room 101–103",
        "token_prefix": "CARD",
        "icon": "HeartPulse",
        "is_active": True,
    },
    {
        "custom_id": "dept_genm",
        "hospital_id": "hosp_city_01",
        "name": "General Medicine",
        "code": "GENM",
        "room": "Room 104–106",
        "token_prefix": "GENM",
        "icon": "Stethoscope",
        "is_active": True,
    },
    {
        "custom_id": "dept_orth",
        "hospital_id": "hosp_city_01",
        "name": "Orthopedics",
        "code": "ORTH",
        "room": "Room 201–202",
        "token_prefix": "ORTH",
        "icon": "Activity",
        "is_active": True,
    },
    {
        "custom_id": "dept_pedi",
        "hospital_id": "hosp_city_01",
        "name": "Pediatrics",
        "code": "PEDI",
        "room": "Room 203–204",
        "token_prefix": "PEDI",
        "icon": "Baby",
        "is_active": True,
    },
    {
        "custom_id": "dept_derm",
        "hospital_id": "hosp_city_01",
        "name": "Dermatology",
        "code": "DERM",
        "room": "Room 301–302",
        "token_prefix": "DERM",
        "icon": "Sparkles",
        "is_active": True,
    },
    {
        "custom_id": "dept_ent",
        "hospital_id": "hosp_city_01",
        "name": "ENT",
        "code": "ENT",
        "room": "Room 303–304",
        "token_prefix": "ENT",
        "icon": "Ear",
        "is_active": True,
    },
]

SEED_DOCTORS = [
    {
        "custom_id": "doc_card_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_card",
        "name": "Dr. Anand Ramanathan",
        "specialty": "Senior Interventional Cardiologist",
        "qualification": "MBBS, MD, DM, FACC",
        "qualifications": ["MBBS", "MD (Gen Med)", "DM (Cardiology)", "FACC"],
        "experience_years": 18,
        "fee": 800,
        "languages": ["English", "Tamil", "Hindi"],
        "gender": "male",
        "bio": "Specialist in coronary angioplasty and preventive cardiology with over 18 years of clinical leadership.",
        "avg_consult_minutes": 12.0,
        "rating_avg": 4.9,
        "rating_count": 512,
        "is_active": True,
        "room": "Room 101",
        "email": "anand.r@cityhospital.example.com",
        "phone": "+91 98404 56789",
    },
    {
        "custom_id": "doc_card_2",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_card",
        "name": "Dr. Meena Raj",
        "specialty": "Consultant Cardiologist & Electrophysiologist",
        "qualification": "MBBS, MD, DNB",
        "qualifications": ["MBBS", "MD", "DNB (Cardiology)"],
        "experience_years": 11,
        "fee": 700,
        "languages": ["English", "Tamil"],
        "gender": "female",
        "bio": "Focus on heart rhythm disorders, pacemaker management, and non-invasive cardiac evaluation.",
        "avg_consult_minutes": 10.0,
        "rating_avg": 4.8,
        "rating_count": 320,
        "is_active": True,
        "room": "Room 102",
        "email": "meena.r@cityhospital.example.com",
        "phone": "+91 98405 67890",
    },
    {
        "custom_id": "doc_genm_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_genm",
        "name": "Dr. Rajesh Deshmukh",
        "specialty": "Senior Consultant Physician",
        "qualification": "MBBS, MD",
        "qualifications": ["MBBS", "MD (Internal Medicine)"],
        "experience_years": 15,
        "fee": 500,
        "languages": ["English", "Hindi", "Marathi"],
        "gender": "male",
        "bio": "Comprehensive internal medicine, diabetes management, and chronic infectious illnesses.",
        "avg_consult_minutes": 9.0,
        "rating_avg": 4.7,
        "rating_count": 640,
        "is_active": True,
        "room": "Room 104",
        "email": "rajesh.d@cityhospital.example.com",
        "phone": "+91 98406 78901",
    },
    {
        "custom_id": "doc_orth_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_orth",
        "name": "Dr. Vikramaditya Seth",
        "specialty": "Senior Orthopedic & Joint Surgeon",
        "qualification": "MBBS, MS, MCh",
        "qualifications": ["MBBS", "MS (Orthopedics)", "MCh"],
        "experience_years": 16,
        "fee": 750,
        "languages": ["English", "Hindi", "Bengali"],
        "gender": "male",
        "bio": "Joint replacement specialist, complex trauma reconstruction, and arthroscopy.",
        "avg_consult_minutes": 14.0,
        "rating_avg": 4.9,
        "rating_count": 480,
        "is_active": True,
        "room": "Room 201",
        "email": "vikram.s@cityhospital.example.com",
        "phone": "+91 98407 89012",
    },
    {
        "custom_id": "doc_pedi_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_pedi",
        "name": "Dr. Meera Nambiar",
        "specialty": "Chief Pediatrician & Neonatologist",
        "qualification": "MBBS, MD",
        "qualifications": ["MBBS", "MD (Pediatrics)", "Fellowship in Neonatology"],
        "experience_years": 14,
        "fee": 650,
        "languages": ["English", "Malayalam", "Tamil"],
        "gender": "female",
        "bio": "Newborn care, developmental milestones, pediatric allergy and asthma.",
        "avg_consult_minutes": 13.0,
        "rating_avg": 4.9,
        "rating_count": 530,
        "is_active": True,
        "room": "Room 203",
        "email": "meera.n@cityhospital.example.com",
        "phone": "+91 98408 90123",
    },
    {
        "custom_id": "doc_derm_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_derm",
        "name": "Dr. Sunita Varma",
        "specialty": "Senior Consultant Dermatologist",
        "qualification": "MBBS, MD",
        "qualifications": ["MBBS", "MD (Dermatology)"],
        "experience_years": 12,
        "fee": 700,
        "languages": ["English", "Hindi", "Telugu"],
        "gender": "female",
        "bio": "Clinical dermatology, trichology, eczema, and psoriasis therapeutics.",
        "avg_consult_minutes": 11.0,
        "rating_avg": 4.8,
        "rating_count": 380,
        "is_active": True,
        "room": "Room 301",
        "email": "sunita.v@cityhospital.example.com",
        "phone": "+91 98409 01234",
    },
]

SEED_USERS = [
    {
        "name": "Suresh Narayanan",
        "phone": "+91 98401 23456",
        "email": "admin.suresh@cityhospital.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp_city_01",
        "preferred_language": "en",
    },
    {
        "name": "Deepa Krishnan",
        "phone": "+91 98402 34567",
        "email": "deepa.k@cityhospital.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp_city_01",
        "preferred_language": "ta",
    },
    {
        "name": "Ganesh Moorthy",
        "phone": "+91 98403 45678",
        "email": "ganesh.m@cityhospital.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp_city_01",
        "preferred_language": "en",
    },
    {
        "name": "Dr. Anand Ramanathan",
        "phone": "+91 98404 56789",
        "email": "anand.r@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "preferred_language": "en",
    },
    {
        "name": "Dr. Meena Raj",
        "phone": "+91 98405 67890",
        "email": "meena.r@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "preferred_language": "ta",
    },
    {
        "name": "Ravi Kumar (Patient Demo)",
        "phone": "+91 98765 43210",
        "email": "patient.ravi@example.com",
        "password": "Password@123",
        "role": "patient",
        "preferred_language": "en",
        "age": 34,
        "gender": "male",
    },
]
