"""ChroniQ Comprehensive Original Seed Data.
Schema-compliant data matching Beanie models for:
- 13 Hospitals across Tamil Nadu
- Clinical Departments
- Verified Doctors
- Multi-role Users (Admins, Receptionists, Doctors, Patients)
- Patient Family Members
- Patient Reviews & Ratings
- Notification Templates
"""

# ==============================================================================
# 1. HOSPITALS (13 Facilities Across Tamil Nadu)
# ==============================================================================

SEED_HOSPITALS = [
    {
        "custom_id": "hosp_city_01",
        "name": "City Hospital",
        "city": "Chennai",
        "address": "42 Anna Salai, Thousand Lights, Chennai 600006",
        "phone": "+91 44 2829 0000",
        "email": "admin@cityhospital.example.com",
        "location": {"type": "Point", "coordinates": [80.2508, 13.0604]},
        "timings": "24x7",
        "facilities": ["Cardiology", "General Medicine", "Orthopedics", "Pediatrics", "Dermatology", "ENT"],
        "rating_avg": 4.8,
        "rating_count": 1420,
        "status": "active",
        "settings": {
            "grace_period_minutes": 10,
            "cancel_window_hours": 2,
            "slot_hold_minutes": 5,
            "walk_ins_enabled": True,
        },
    },
    {
        "custom_id": "hosp-001",
        "name": "Apollo Hospitals",
        "city": "Chennai",
        "address": "21 Greams Lane, Thousand Lights, Chennai — 600 006",
        "phone": "+91 44 2829 3333",
        "email": "info@apollo.example.com",
        "location": {"type": "Point", "coordinates": [80.2496, 13.0604]},
        "timings": "24x7",
        "facilities": ["Cardiology", "Neurology", "Oncology", "Emergency", "Nephrology", "Gastroenterology"],
        "rating_avg": 4.7,
        "rating_count": 2843,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-002",
        "name": "MIOT International",
        "city": "Chennai",
        "address": "4/112 Mount Poonamallee Rd, Manapakkam, Chennai — 600 089",
        "phone": "+91 44 4200 2288",
        "email": "info@miot.example.com",
        "location": {"type": "Point", "coordinates": [80.1696, 13.0261]},
        "timings": "24x7",
        "facilities": ["Orthopedics", "Rheumatology", "Spine Surgery", "Physiotherapy", "Sports Medicine"],
        "rating_avg": 4.5,
        "rating_count": 1920,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-003",
        "name": "Kovai Medical Center",
        "city": "Coimbatore",
        "address": "Avanashi Road, Civil Aerodrome Post, Coimbatore — 641 014",
        "phone": "+91 422 4323 800",
        "email": "info@kmch.example.com",
        "location": {"type": "Point", "coordinates": [77.0033, 11.0168]},
        "timings": "24x7",
        "facilities": ["Cardiology", "Pediatrics", "Urology", "Gastroenterology", "Pulmonology"],
        "rating_avg": 4.6,
        "rating_count": 1538,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-004",
        "name": "Fortis Malar Hospital",
        "city": "Chennai",
        "address": "52 1st Main Rd, Gandhi Nagar, Adyar, Chennai — 600 020",
        "phone": "+91 44 4289 2222",
        "email": "info@fortis.example.com",
        "location": {"type": "Point", "coordinates": [80.2504, 13.0066]},
        "timings": "8 AM – 10 PM",
        "facilities": ["Cardiac Sciences", "Orthopedics", "Nephrology", "Dermatology", "General Medicine"],
        "rating_avg": 4.4,
        "rating_count": 1201,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-005",
        "name": "Aravind Eye Hospital",
        "city": "Madurai",
        "address": "1 Anna Nagar, Madurai — 625 020",
        "phone": "+91 452 435 6100",
        "email": "info@aravind.example.com",
        "location": {"type": "Point", "coordinates": [78.1198, 9.9252]},
        "timings": "7 AM – 8 PM",
        "facilities": ["Ophthalmology", "Retina", "Glaucoma", "Paediatric Eye Care", "Cornea"],
        "rating_avg": 4.9,
        "rating_count": 4120,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-006",
        "name": "Sri Ramakrishna Hospital",
        "city": "Coimbatore",
        "address": "395 Sarojini Naidu Rd, Sidhapudur, Coimbatore — 641 044",
        "phone": "+91 422 4500 000",
        "email": "info@ramakrishna.example.com",
        "location": {"type": "Point", "coordinates": [76.9648, 11.0054]},
        "timings": "24x7",
        "facilities": ["Neurology", "General Surgery", "Gynaecology", "Pulmonology", "Psychiatry"],
        "rating_avg": 4.3,
        "rating_count": 988,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-007",
        "name": "CMC Vellore",
        "city": "Vellore",
        "address": "IDA Scudder Rd, Vellore — 632 004",
        "phone": "+91 416 228 1000",
        "email": "info@cmcvellore.example.com",
        "location": {"type": "Point", "coordinates": [79.1325, 12.9241]},
        "timings": "24x7",
        "facilities": ["General Medicine", "Neurology", "Oncology", "Pediatrics", "Psychiatry", "Cardiology"],
        "rating_avg": 4.8,
        "rating_count": 5621,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-008",
        "name": "Meenakshi Mission Hospital",
        "city": "Madurai",
        "address": "Lake Area, Melur Rd, Madurai — 625 107",
        "phone": "+91 452 435 8888",
        "email": "info@meenakshimission.example.com",
        "location": {"type": "Point", "coordinates": [78.1314, 9.9616]},
        "timings": "24x7",
        "facilities": ["Cardiology", "Gynaecology", "Endocrinology", "General Surgery", "Urology"],
        "rating_avg": 4.2,
        "rating_count": 743,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-009",
        "name": "Kauvery Hospital",
        "city": "Trichy",
        "address": "104A, 6th Cross, Tenur, Trichy — 620 017",
        "phone": "+91 431 404 0404",
        "email": "info@kauvery.example.com",
        "location": {"type": "Point", "coordinates": [78.7047, 10.7905]},
        "timings": "24x7",
        "facilities": ["Cardiology", "Nephrology", "Urology", "Gastroenterology", "Neurology"],
        "rating_avg": 4.5,
        "rating_count": 1102,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-010",
        "name": "SIMS Hospital",
        "city": "Chennai",
        "address": "1, Jawaharlal Nehru Salai, Vadapalani, Chennai — 600 026",
        "phone": "+91 44 4396 3900",
        "email": "info@sims.example.com",
        "location": {"type": "Point", "coordinates": [80.2120, 13.0527]},
        "timings": "8 AM – 9 PM",
        "facilities": ["Orthopedics", "Neurology", "General Medicine", "Rheumatology", "Dermatology"],
        "rating_avg": 4.1,
        "rating_count": 672,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-011",
        "name": "G. Kuppuswamy Naidu Memorial Hospital",
        "city": "Coimbatore",
        "address": "Post Box 6327, Nethaji Rd, Coimbatore — 641 001",
        "phone": "+91 422 234 1212",
        "email": "info@gknm.example.com",
        "location": {"type": "Point", "coordinates": [76.9671, 11.0133]},
        "timings": "7 AM – 7 PM",
        "facilities": ["General Medicine", "Gynaecology", "Pediatrics", "Dermatology", "Pulmonology"],
        "rating_avg": 4.0,
        "rating_count": 538,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
    {
        "custom_id": "hosp-012",
        "name": "Mahatma Eye Hospital",
        "city": "Trichy",
        "address": "6, Seshapuram, Trichy — 620 002",
        "phone": "+91 431 277 4080",
        "email": "info@mahatma.example.com",
        "location": {"type": "Point", "coordinates": [78.6856, 10.8050]},
        "timings": "8 AM – 6 PM",
        "facilities": ["Ophthalmology", "Retina", "Cornea", "Cataract Surgery", "Glaucoma"],
        "rating_avg": 4.6,
        "rating_count": 1890,
        "status": "active",
        "settings": {"grace_period_minutes": 10, "cancel_window_hours": 2, "slot_hold_minutes": 5, "walk_ins_enabled": True},
    },
]

# Alias for backward compatibility
SEED_HOSPITAL = SEED_HOSPITALS[0]


# ==============================================================================
# 2. DEPARTMENTS
# ==============================================================================

SEED_DEPARTMENTS = [
    # City Hospital (hosp_city_01)
    {"custom_id": "dept_card", "hospital_id": "hosp_city_01", "name": "Cardiology", "room": "Room 101–103", "token_prefix": "CARD", "is_active": True},
    {"custom_id": "dept_genm", "hospital_id": "hosp_city_01", "name": "General Medicine", "room": "Room 104–106", "token_prefix": "GENM", "is_active": True},
    {"custom_id": "dept_orth", "hospital_id": "hosp_city_01", "name": "Orthopedics", "room": "Room 201–202", "token_prefix": "ORTH", "is_active": True},
    {"custom_id": "dept_pedi", "hospital_id": "hosp_city_01", "name": "Pediatrics", "room": "Room 203–204", "token_prefix": "PEDI", "is_active": True},
    {"custom_id": "dept_derm", "hospital_id": "hosp_city_01", "name": "Dermatology", "room": "Room 301–302", "token_prefix": "DERM", "is_active": True},
    {"custom_id": "dept_ent",  "hospital_id": "hosp_city_01", "name": "ENT", "room": "Room 303–304", "token_prefix": "ENT", "is_active": True},

    # Apollo Hospitals (hosp-001)
    {"custom_id": "dept_apol_card", "hospital_id": "hosp-001", "name": "Cardiology", "room": "Block A, Room 101", "token_prefix": "CARD", "is_active": True},
    {"custom_id": "dept_apol_neur", "hospital_id": "hosp-001", "name": "Neurology", "room": "Block A, Room 201", "token_prefix": "NEUR", "is_active": True},
    {"custom_id": "dept_apol_onco", "hospital_id": "hosp-001", "name": "Oncology", "room": "Block B, Room 105", "token_prefix": "ONCO", "is_active": True},
    {"custom_id": "dept_apol_neph", "hospital_id": "hosp-001", "name": "Nephrology", "room": "Block B, Room 205", "token_prefix": "NEPH", "is_active": True},
    {"custom_id": "dept_apol_gast", "hospital_id": "hosp-001", "name": "Gastroenterology", "room": "Block C, Room 102", "token_prefix": "GAST", "is_active": True},

    # MIOT International (hosp-002)
    {"custom_id": "dept_miot_orth", "hospital_id": "hosp-002", "name": "Orthopedics", "room": "Suite 101", "token_prefix": "ORTH", "is_active": True},
    {"custom_id": "dept_miot_spin", "hospital_id": "hosp-002", "name": "Spine Surgery", "room": "Suite 104", "token_prefix": "SPIN", "is_active": True},
    {"custom_id": "dept_miot_phys", "hospital_id": "hosp-002", "name": "Physiotherapy", "room": "Rehab Wing", "token_prefix": "PHYS", "is_active": True},

    # Kovai Medical Center (hosp-003)
    {"custom_id": "dept_kmch_card", "hospital_id": "hosp-003", "name": "Cardiology", "room": "Tower 1, Rm 301", "token_prefix": "CARD", "is_active": True},
    {"custom_id": "dept_kmch_pedi", "hospital_id": "hosp-003", "name": "Pediatrics", "room": "Tower 2, Rm 201", "token_prefix": "PEDI", "is_active": True},
    {"custom_id": "dept_kmch_gast", "hospital_id": "hosp-003", "name": "Gastroenterology", "room": "Tower 1, Rm 402", "token_prefix": "GAST", "is_active": True},

    # Aravind Eye Hospital (hosp-005)
    {"custom_id": "dept_arav_opht", "hospital_id": "hosp-005", "name": "Ophthalmology", "room": "Floor 1, Clinic A", "token_prefix": "EYE", "is_active": True},
    {"custom_id": "dept_arav_reti", "hospital_id": "hosp-005", "name": "Retina", "room": "Floor 2, Clinic B", "token_prefix": "RETI", "is_active": True},

    # CMC Vellore (hosp-007)
    {"custom_id": "dept_cmcv_neur", "hospital_id": "hosp-007", "name": "Neurology", "room": "Main OPD 12", "token_prefix": "NEUR", "is_active": True},
    {"custom_id": "dept_cmcv_pedi", "hospital_id": "hosp-007", "name": "Pediatrics", "room": "Pediatric Pavilion", "token_prefix": "PEDI", "is_active": True},
    {"custom_id": "dept_cmcv_card", "hospital_id": "hosp-007", "name": "Cardiology", "room": "Heart Centre 4", "token_prefix": "CARD", "is_active": True},
    {"custom_id": "dept_cmcv_psyc", "hospital_id": "hosp-007", "name": "Psychiatry", "room": "Mental Health Centre", "token_prefix": "PSYC", "is_active": True},
]


# ==============================================================================
# 3. DOCTORS
# ==============================================================================

SEED_DOCTORS = [
    # ── City Hospital (hosp_city_01) ──────────────────────────────────────────
    {
        "custom_id": "doc_card_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_card",
        "name": "Dr. Anand Ramanathan",
        "specialty": "Cardiology",
        "qualifications": ["MBBS", "MD (Gen Med)", "DM (Cardiology)", "FACC"],
        "experience_years": 18,
        "fee": 800,
        "languages": ["English", "Tamil", "Hindi"],
        "gender": "male",
        "bio": "Specialist in coronary angioplasty and preventive cardiology with over 18 years of clinical leadership.",
        "avg_consult_minutes": 12.0,
        "rating_avg": 4.9,
        "rating_count": 512,
        "is_active": True,
        "room": "Room 101",
    },
    {
        "custom_id": "doc_card_2",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_card",
        "name": "Dr. Meena Raj",
        "specialty": "Cardiology",
        "qualifications": ["MBBS", "MD", "DNB (Cardiology)"],
        "experience_years": 11,
        "fee": 700,
        "languages": ["English", "Tamil"],
        "gender": "female",
        "bio": "Focus on heart rhythm disorders, pacemaker management, and non-invasive cardiac evaluation.",
        "avg_consult_minutes": 10.0,
        "rating_avg": 4.8,
        "rating_count": 320,
        "is_active": True,
        "room": "Room 102",
    },
    {
        "custom_id": "doc_genm_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_genm",
        "name": "Dr. Rajesh Deshmukh",
        "specialty": "General Medicine",
        "qualifications": ["MBBS", "MD (Internal Medicine)"],
        "experience_years": 15,
        "fee": 500,
        "languages": ["English", "Hindi", "Marathi"],
        "gender": "male",
        "bio": "Comprehensive internal medicine, diabetes management, and chronic infectious illnesses.",
        "avg_consult_minutes": 9.0,
        "rating_avg": 4.7,
        "rating_count": 640,
        "is_active": True,
        "room": "Room 104",
    },
    {
        "custom_id": "doc_orth_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_orth",
        "name": "Dr. Vikramaditya Seth",
        "specialty": "Orthopedics",
        "qualifications": ["MBBS", "MS (Orthopedics)", "MCh"],
        "experience_years": 16,
        "fee": 750,
        "languages": ["English", "Hindi", "Bengali"],
        "gender": "male",
        "bio": "Joint replacement specialist, complex trauma reconstruction, and arthroscopy.",
        "avg_consult_minutes": 14.0,
        "rating_avg": 4.9,
        "rating_count": 480,
        "is_active": True,
        "room": "Room 201",
    },
    {
        "custom_id": "doc_pedi_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_pedi",
        "name": "Dr. Meera Nambiar",
        "specialty": "Pediatrics",
        "qualifications": ["MBBS", "MD (Pediatrics)", "Fellowship in Neonatology"],
        "experience_years": 14,
        "fee": 650,
        "languages": ["English", "Malayalam", "Tamil"],
        "gender": "female",
        "bio": "Newborn care, developmental milestones, pediatric allergy and asthma.",
        "avg_consult_minutes": 13.0,
        "rating_avg": 4.9,
        "rating_count": 530,
        "is_active": True,
        "room": "Room 203",
    },
    {
        "custom_id": "doc_derm_1",
        "hospital_id": "hosp_city_01",
        "department_id": "dept_derm",
        "name": "Dr. Sunita Varma",
        "specialty": "Dermatology",
        "qualifications": ["MBBS", "MD (Dermatology)"],
        "experience_years": 12,
        "fee": 700,
        "languages": ["English", "Hindi", "Telugu"],
        "gender": "female",
        "bio": "Clinical dermatology, trichology, eczema, and psoriasis therapeutics.",
        "avg_consult_minutes": 11.0,
        "rating_avg": 4.8,
        "rating_count": 380,
        "is_active": True,
        "room": "Room 301",
    },

    # ── Apollo Hospitals (hosp-001) ───────────────────────────────────────────
    {
        "custom_id": "doc-001",
        "hospital_id": "hosp-001",
        "department_id": "dept_apol_card",
        "name": "Dr. Priya Nair",
        "specialty": "Cardiology",
        "qualifications": ["MBBS", "MD", "DM (Cardiology)"],
        "experience_years": 18,
        "fee": 1200,
        "languages": ["Tamil", "English", "Hindi"],
        "gender": "female",
        "bio": "Senior interventional cardiologist with 18 years experience in complex coronary interventions.",
        "avg_consult_minutes": 15.0,
        "rating_avg": 4.8,
        "rating_count": 392,
        "is_active": True,
        "room": "Apollo Block A-101",
    },
    {
        "custom_id": "doc-002",
        "hospital_id": "hosp-001",
        "department_id": "dept_apol_neur",
        "name": "Dr. Ramesh Kumar",
        "specialty": "Neurology",
        "qualifications": ["MBBS", "MD", "DM (Neurology)"],
        "experience_years": 22,
        "fee": 1500,
        "languages": ["Tamil", "English"],
        "gender": "male",
        "bio": "Specialising in epilepsy, movement disorders, and neuro-immunology with 22 years of practice.",
        "avg_consult_minutes": 15.0,
        "rating_avg": 4.9,
        "rating_count": 511,
        "is_active": True,
        "room": "Apollo Block A-201",
    },
    {
        "custom_id": "doc-003",
        "hospital_id": "hosp-001",
        "department_id": "dept_apol_onco",
        "name": "Dr. Anitha Suresh",
        "specialty": "Oncology",
        "qualifications": ["MBBS", "MD", "DNB"],
        "experience_years": 14,
        "fee": 1800,
        "languages": ["Tamil", "English"],
        "gender": "female",
        "bio": "Medical oncologist specialising in breast, lung, and gastrointestinal cancers.",
        "avg_consult_minutes": 20.0,
        "rating_avg": 4.6,
        "rating_count": 278,
        "is_active": True,
        "room": "Apollo Block B-105",
    },

    # ── MIOT International (hosp-002) ─────────────────────────────────────────
    {
        "custom_id": "doc-006",
        "hospital_id": "hosp-002",
        "department_id": "dept_miot_orth",
        "name": "Dr. Suresh Babu",
        "specialty": "Orthopedics",
        "qualifications": ["MBBS", "MS (Ortho)", "MCh"],
        "experience_years": 20,
        "fee": 1400,
        "languages": ["Tamil", "English"],
        "gender": "male",
        "bio": "Leading joint-replacement surgeon, performed over 8,000 knee and hip replacements.",
        "avg_consult_minutes": 15.0,
        "rating_avg": 4.9,
        "rating_count": 640,
        "is_active": True,
        "room": "MIOT Suite 101",
    },

    # ── Kovai Medical Center (hosp-003) ───────────────────────────────────────
    {
        "custom_id": "doc-009",
        "hospital_id": "hosp-003",
        "department_id": "dept_kmch_card",
        "name": "Dr. Murugan Selvam",
        "specialty": "Cardiology",
        "qualifications": ["MBBS", "MD", "DM"],
        "experience_years": 16,
        "fee": 1100,
        "languages": ["Tamil", "English"],
        "gender": "male",
        "bio": "Primary angioplasty, complex bifurcation stenting, and heart failure management.",
        "avg_consult_minutes": 12.0,
        "rating_avg": 4.7,
        "rating_count": 310,
        "is_active": True,
        "room": "KMCH Tower 1-301",
    },
    {
        "custom_id": "doc-010",
        "hospital_id": "hosp-003",
        "department_id": "dept_kmch_pedi",
        "name": "Dr. Deepa Chandran",
        "specialty": "Pediatrics",
        "qualifications": ["MBBS", "MD", "Fellowship"],
        "experience_years": 12,
        "fee": 800,
        "languages": ["Tamil", "English", "Malayalam"],
        "gender": "female",
        "bio": "Heads the NICU at Kovai Medical Center, caring for children from newborns to adolescents.",
        "avg_consult_minutes": 12.0,
        "rating_avg": 4.8,
        "rating_count": 445,
        "is_active": True,
        "room": "KMCH Tower 2-201",
    },

    # ── Aravind Eye Hospital (hosp-005) ───────────────────────────────────────
    {
        "custom_id": "doc-012",
        "hospital_id": "hosp-005",
        "department_id": "dept_arav_opht",
        "name": "Dr. Meena Krishnan",
        "specialty": "Ophthalmology",
        "qualifications": ["MBBS", "MS", "DNB"],
        "experience_years": 17,
        "fee": 700,
        "languages": ["Tamil", "English"],
        "gender": "female",
        "bio": "Comprehensive ophthalmologist with over 25,000 cataract surgeries performed.",
        "avg_consult_minutes": 10.0,
        "rating_avg": 4.9,
        "rating_count": 820,
        "is_active": True,
        "room": "Aravind Clinic A",
    },

    # ── CMC Vellore (hosp-007) ───────────────────────────────────────────────
    {
        "custom_id": "doc-016",
        "hospital_id": "hosp-007",
        "department_id": "dept_cmcv_card",
        "name": "Dr. Ranjit Cherian",
        "specialty": "Cardiology",
        "qualifications": ["MBBS", "MD", "DM", "FACC"],
        "experience_years": 28,
        "fee": 2000,
        "languages": ["English", "Tamil"],
        "gender": "male",
        "bio": "Fellow of ACC, pioneer of catheterisation techniques and complex left-main PCI.",
        "avg_consult_minutes": 15.0,
        "rating_avg": 4.9,
        "rating_count": 1042,
        "is_active": True,
        "room": "CMC Heart Centre 4",
    },
]


# ==============================================================================
# 4. USERS (Roles across all facilities)
# ==============================================================================

SEED_USERS = [
    # ── Hospital Admins ───────────────────────────────────────────────────────
    {
        "name": "Suresh Narayanan",
        "phone": "+91 98401 23456",
        "email": "admin.suresh@cityhospital.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp_city_01",
        "preferred_language": "en",
    },
    {
        "name": "Apollo Admin",
        "phone": "+91 98401 11111",
        "email": "admin.apollo@apollo.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp-001",
        "preferred_language": "en",
    },

    # ── Receptionists ─────────────────────────────────────────────────────────
    {
        "name": "Deepa Krishnan",
        "phone": "+91 98402 34567",
        "email": "deepa.k@cityhospital.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp_city_01",
        "preferred_language": "ta",
    },
    {
        "name": "Ganesh Moorthy",
        "phone": "+91 98403 45678",
        "email": "ganesh.m@cityhospital.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp_city_01",
        "preferred_language": "en",
    },

    # ── Doctor Accounts (Linked to Seed Doctors) ──────────────────────────────
    {
        "name": "Dr. Anand Ramanathan",
        "phone": "+91 98404 56789",
        "email": "anand.r@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "linked_doctor_id": "doc_card_1",
        "preferred_language": "en",
    },
    {
        "name": "Dr. Meena Raj",
        "phone": "+91 98405 67890",
        "email": "meena.r@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "linked_doctor_id": "doc_card_2",
        "preferred_language": "ta",
    },
    {
        "name": "Dr. Rajesh Deshmukh",
        "phone": "+91 98406 78901",
        "email": "rajesh.d@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "linked_doctor_id": "doc_genm_1",
        "preferred_language": "hi",
    },
    {
        "name": "Dr. Vikramaditya Seth",
        "phone": "+91 98407 89012",
        "email": "vikram.s@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "linked_doctor_id": "doc_orth_1",
        "preferred_language": "en",
    },
    {
        "name": "Dr. Meera Nambiar",
        "phone": "+91 98408 90123",
        "email": "meera.n@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "linked_doctor_id": "doc_pedi_1",
        "preferred_language": "ml",
    },
    {
        "name": "Dr. Sunita Varma",
        "phone": "+91 98409 01234",
        "email": "sunita.v@cityhospital.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp_city_01",
        "linked_doctor_id": "doc_derm_1",
        "preferred_language": "te",
    },
    {
        "name": "Dr. Priya Nair",
        "phone": "+91 98400 00001",
        "email": "priya.nair@apollo.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp-001",
        "linked_doctor_id": "doc-001",
        "preferred_language": "ta",
    },
    # ── Additional Multi-Hospital Staff (Madurai, Chennai, Coimbatore) ──
    {
        "name": "Priya Sundaram",
        "phone": "+91 98402 11333",
        "email": "priya.s@apollo.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp-001",
        "preferred_language": "ta",
    },
    {
        "name": "Selvam Raghavan",
        "phone": "+91 98401 22111",
        "email": "admin.selvam@miot.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp-002",
        "preferred_language": "en",
    },
    {
        "name": "Karthika Natarajan",
        "phone": "+91 98402 22222",
        "email": "karthika.n@miot.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp-002",
        "preferred_language": "ta",
    },
    {
        "name": "M. Senthilkumar",
        "phone": "+91 94431 33111",
        "email": "admin.senthil@aravind.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp-005",
        "preferred_language": "ta",
    },
    {
        "name": "Revathi Venkataraman",
        "phone": "+91 94432 33222",
        "email": "revathi.v@aravind.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp-005",
        "preferred_language": "ta",
    },
    {
        "name": "Dr. Meena Krishnan",
        "phone": "+91 94434 33444",
        "email": "meena.k@aravind.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp-005",
        "linked_doctor_id": "doc-012",
        "preferred_language": "ta",
    },
    {
        "name": "B. Ramakrishnan",
        "phone": "+91 94431 44111",
        "email": "admin.ramakrishnan@meenakshimission.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp-008",
        "preferred_language": "en",
    },
    {
        "name": "Anitha Balakrishnan",
        "phone": "+91 94432 44222",
        "email": "anitha.b@meenakshimission.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp-008",
        "preferred_language": "ta",
    },
    {
        "name": "Dr. K. Senthil Nathan",
        "phone": "+91 98422 55111",
        "email": "admin.senthil@kmch.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp-003",
        "preferred_language": "en",
    },
    {
        "name": "Divya Murugesan",
        "phone": "+91 98423 55222",
        "email": "divya.m@kmch.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp-003",
        "preferred_language": "ta",
    },
    {
        "name": "Dr. Murugan Selvam",
        "phone": "+91 98425 55444",
        "email": "murugan.s@kmch.example.com",
        "password": "Password@123",
        "role": "doctor",
        "hospital_id": "hosp-003",
        "linked_doctor_id": "doc-009",
        "preferred_language": "ta",
    },
    {
        "name": "V. Sukumaran",
        "phone": "+91 98421 66111",
        "email": "admin.sukumaran@ramakrishna.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp-006",
        "preferred_language": "en",
    },
    {
        "name": "Shanthi Swaminathan",
        "phone": "+91 98422 66222",
        "email": "shanthi.s@ramakrishna.example.com",
        "password": "Password@123",
        "role": "receptionist",
        "hospital_id": "hosp-006",
        "preferred_language": "ta",
    },
    {
        "name": "R. Balasubramanian",
        "phone": "+91 98421 77111",
        "email": "admin.bala@gknm.example.com",
        "password": "Password@123",
        "role": "hospital_admin",
        "hospital_id": "hosp-011",
        "preferred_language": "en",
    },

    # ── Patients ──────────────────────────────────────────────────────────────
    {
        "name": "Ravi Kumar",
        "phone": "+91 98765 43210",
        "email": "patient.ravi@example.com",
        "password": "Password@123",
        "role": "patient",
        "preferred_language": "en",
        "age": 34,
        "gender": "male",
    },
    {
        "name": "Priya Sharma",
        "phone": "+91 98765 43211",
        "email": "priya.s@example.com",
        "password": "Password@123",
        "role": "patient",
        "preferred_language": "en",
        "age": 29,
        "gender": "female",
    },
    {
        "name": "Karthik Raja",
        "phone": "+91 98765 43212",
        "email": "karthik.r@example.com",
        "password": "Password@123",
        "role": "patient",
        "preferred_language": "ta",
        "age": 42,
        "gender": "male",
    },
    {
        "name": "Ananya Rao",
        "phone": "+91 98765 43213",
        "email": "ananya.r@example.com",
        "password": "Password@123",
        "role": "patient",
        "preferred_language": "en",
        "age": 31,
        "gender": "female",
    },
]


# ==============================================================================
# 5. FAMILY MEMBERS (Linked to Ravi Kumar)
# ==============================================================================

SEED_FAMILY_MEMBERS = [
    {"name": "Kavitha Ravi", "age": 32, "gender": "female", "relation": "spouse"},
    {"name": "Aarav Kumar", "age": 6, "gender": "male", "relation": "son"},
    {"name": "S. Kumar", "age": 62, "gender": "male", "relation": "father"},
    {"name": "Lakshmi Kumar", "age": 58, "gender": "female", "relation": "mother"},
]


# ==============================================================================
# 6. REVIEWS & RATINGS
# ==============================================================================

SEED_REVIEWS = [
    {
        "doctor_id": "doc_card_1",
        "hospital_id": "hosp_city_01",
        "patient_name": "Suresh M.",
        "doctor_rating": 5,
        "hospital_rating": 5,
        "comment": "Dr. Anand Ramanathan explained my angioplasty results in terms I could easily understand. Calm and reassuring throughout.",
        "wait_as_expected": "as_expected",
        "tags": ["Thorough", "Clear Explanation", "Professional"],
    },
    {
        "doctor_id": "doc_card_1",
        "hospital_id": "hosp_city_01",
        "patient_name": "Kamala V.",
        "doctor_rating": 5,
        "hospital_rating": 4,
        "comment": "He spent 20 minutes reviewing my ECG and lifestyle habits. Best cardiology consultation I have had.",
        "wait_as_expected": "shorter",
        "tags": ["Attentive", "Friendly Staff"],
    },
    {
        "doctor_id": "doc_orth_1",
        "hospital_id": "hosp_city_01",
        "patient_name": "Aravind M.",
        "doctor_rating": 5,
        "hospital_rating": 5,
        "comment": "Dr. Seth treated my ligament injury effectively. He recommended conservative physio first instead of surgery.",
        "wait_as_expected": "as_expected",
        "tags": ["Expertise", "Honest Advice"],
    },
    {
        "doctor_id": "doc-001",
        "hospital_id": "hosp-001",
        "patient_name": "Preethi S.",
        "doctor_rating": 5,
        "hospital_rating": 5,
        "comment": "Outstanding cardiac care at Apollo. Dr. Priya Nair was exceptionally thorough. Highly recommended.",
        "wait_as_expected": "as_expected",
        "tags": ["World-Class", "Compassionate"],
    },
]


# ==============================================================================
# 7. NOTIFICATION TEMPLATES
# ==============================================================================

SEED_NOTIFICATION_TEMPLATES = [
    {
        "hospital_id": "hosp_city_01",
        "type": "booking_confirmed",
        "label": "Booking Confirmation",
        "channels": {"in_app": True, "email": True, "sms": True},
        "template_text": "Your appointment with {doctor_name} at {hospital_name} is confirmed for {date_time}. Booking code: {booking_code}.",
        "variables": ["doctor_name", "hospital_name", "date_time", "booking_code"],
    },
    {
        "hospital_id": "hosp_city_01",
        "type": "you_are_next",
        "label": "Token Called Alert",
        "channels": {"in_app": True, "email": False, "sms": True},
        "template_text": "Token {token} please proceed to {room} for consultation with {doctor_name}.",
        "variables": ["token", "room", "doctor_name"],
    },
    {
        "hospital_id": "hosp_city_01",
        "type": "doctor_delayed",
        "label": "Doctor Delay Notice",
        "channels": {"in_app": True, "email": False, "sms": True},
        "template_text": "Notice: Dr. {doctor_name} is running {minutes_delayed} minutes late. Your estimated consult time is updated on live queue.",
        "variables": ["doctor_name", "minutes_delayed"],
    },
    {
        "hospital_id": "hosp_city_01",
        "type": "reminder",
        "label": "24-Hour Reminder",
        "channels": {"in_app": True, "email": True, "sms": False},
        "template_text": "Reminder: Your appointment with {doctor_name} at {hospital_name} is scheduled for tomorrow at {time}.",
        "variables": ["doctor_name", "hospital_name", "time"],
    },
]
